### ISSUE TITLE
Request: Subitems in the Todo list

### ISSUE THREAD

**Issue by MHolkamp** [CalebJohn/joplin-inline-todo#4]
Hi there,

It would be nice to have have subitem in the list;

- [  ] @ToDo //2022-05-30 Head Item --> Shown
  - [ ] @ToDo //2022-05-05 Second Item --> Not shown in current version
  - [ ] @ToDo //2022-05-07 Third Item --> Not shown in current version

**Comment by CalebJohn** [comment]
This has been fixed in version v1.1.1 (deployed just now, so it should be available within the hour).

Just a note though, subitems won't maintain their dependence on the parent item. So they will be out-of-order in the summary note. If you want them in order you can prefix each item with a number.

example
- [ ] @todo //2022-05-30 1 Head Item --> Shown
  - [ ] @todo //2022-05-05 2 Second Item --> Now shown in current version
  - [ ] @todo //2022-05-07 3 Third Item --> Now shown in current version
